### ISSUE TITLE
Remember selected network

### ISSUE THREAD

**Issue by prybalko** [paritytech/metadata-portal#43]
As a user,
When I choose a network on the selector
I'd like it to be preserved between page refreshes.
So I don't have to select it every time manually.

**Comment by prybalko** [comment]
@wirednkod I beleive that would require adding `onChange` argument to the `NetworkSlider`

**Comment by wirednkod** [comment]
> @wirednkod ~I beleive that would require adding `onChange` handler to the `NetworkSlider`~ Never mind, there is a `setNetwork` handler that seems to work exactly like `onChange`. Please correct me if I'm wrong

setNetwork is actually the function that is passed as a prop to the component in order to "set" on parent container the network that was selected.
In order to remember the selected network for page refreshes, you can set the selection in the localStorage and then pass it to the [currentName](https://github.com/paritytech/metadata-portal/blob/master/src/components/App.tsx#L21) instead of receiving the 1st from the getChains or defaulting to "polkadot".

Actually let me implement this for you, if you dont mind - as I realized there is a minor fix that needs to be done on the mottled library concerning default network
